In [ ]:

from src.raw_data import load_raw_data
from src.clean_data import load_cleaned_data
from src.x_and_y import make_x_and_y, train_test_split_xy
from src.model import train_logreg, train_boosted, print_metrics
from src.scrape import *
from src.inference import *

from src.odds import *

from IPython.display import display
import pandas as pd

def printer(df_dict: dict):
    
    for name, df in df_dict.items():
        print(name, df.shape)
        display(df.head(5))

def main():

    #get raw data, 5 dataframes from github user's scrape of ufc websites
    #so data is included, no external download, fully intergrated into pipeline
    raw = load_raw_data()
    print("STEP 1 RAW DATA\n")
    printer(raw)
    
    #clean all data and make multiple useful utility dataframes, as shown
    cleaned = load_cleaned_data(raw)
    print("\nSTEP 2 CLEANED\n")
    printer(cleaned)

    TRAIN_SIZE = 0.8

    #get x, y and x_train, x_test, y_train, y_test from cleaned["full_sym"]
    print("\nSTEP 3 XY, XY_SPLITS\n")
    xy, xy_splits = make_x_and_y(cleaned["full_sym"], train_size=TRAIN_SIZE)
    printer(xy)
    printer(xy_splits)
    
    #trained both logistic regression and boosted decision tree models and giving info/metrics
    print("\nSTEP 4 MODELS\n")
    model_logreg, model_logreg_metrics = train_logreg(xy_splits)
    model_boosted, model_boosted_metrics = train_boosted(xy_splits)
    print_metrics("LOGREG", model_logreg, model_logreg_metrics)
    print("\n")
    print_metrics("BOOSTED", model_boosted, model_boosted_metrics)

    #showing most productive features for determining if a fighter wins/loses
    print("\nSTEP 4.5 ODDS RATIOS\n")
    odds_df = get_logreg_odds_ratios(
        model_logreg,
        xy_splits["x_train"].columns
    )
    display(odds_df.head(5))
    display(odds_df.tail(5))


    #scraped upcoming event info to get all future fights for inference, 
    #pulled from http://ufcstats.com/statistics/events/upcoming
    print("\nSTEP 5 SCRAPE UPCOMING EVENT INFO\n")
    events_final = get_upcoming_fights_grouped()
    for d in events_final:
        print()
        for k,v in d.items():
            print(f"{k}: {v}")

    #use scraped infor to predict all fights with logreg model as it is interpretable, performs well
    print("\nSTEP 6 PREDICT ALL UPCOMING FIGHTS\n")
    predictions = predict_upcoming_events(events_final, cleaned, model_logreg, xy_splits["x_train"].columns)
    print_predictions(predictions)

    #storing predictions in dataframe for clean access, potential analytics
    print("\nSTEP 7 STORE PREDICTIONS IN DB\n")
    predictions_df = predictions_to_df(predictions)
    display(predictions_df.head(10))


main()

STEP 1 RAW DATA

event_details (770, 4)

,event,url,date,location
0,UFC Fight Night: Burns vs. Malott,http://ufcstats.com/event-details/c3ac8d0da7b0...,"April 18, 2026","Winnipeg, Manitoba, Canada"
1,UFC 327: Prochazka vs. Ulberg,http://ufcstats.com/event-details/f3eb664db7fb...,"April 11, 2026","Miami, Florida, USA"
2,UFC Fight Night: Moicano vs. Duncan,http://ufcstats.com/event-details/9a70f67ad218...,"April 04, 2026","Las Vegas, Nevada, USA"
3,UFC Fight Night: Adesanya vs. Pyfer,http://ufcstats.com/event-details/5c38639f860a...,"March 28, 2026","Seattle, Washington, USA"
4,UFC Fight Night: Evloev vs. Murphy,http://ufcstats.com/event-details/69108cb8b32e...,"March 21, 2026","London, England, United Kingdom"

fight_details (8649, 3)

,event,bout,url
0,UFC Fight Night: Burns vs. Malott,Gilbert Burns vs. Mike Malott,http://ufcstats.com/fight-details/32054bf2b36b...
1,UFC Fight Night: Burns vs. Malott,Kyler Phillips vs. Charles Jourdain,http://ufcstats.com/fight-details/b5299e5b9460...
2,UFC Fight Night: Burns vs. Malott,Mandel Nallo vs. Jai Herbert,http://ufcstats.com/fight-details/e644218737c1...
3,UFC Fight Night: Burns vs. Malott,Jasmine Jasudavicius vs. Karine Silva,http://ufcstats.com/fight-details/5a209522211d...
4,UFC Fight Night: Burns vs. Malott,Thiago Moises vs. Gauge Young,http://ufcstats.com/fight-details/a661c0bee7c8...

results (8649, 11)

,event,bout,outcome,weightclass,method,round,time,time format,referee,details,url
0,UFC Fight Night: Burns vs. Malott,Gilbert Burns vs. Mike Malott,L/W,Welterweight Bout,KO/TKO,3,2:08,5 Rnd (5-5-5-5-5),Herb Dean,Punches to Head On Ground,http://ufcstats.com/fight-details/32054bf2b36b...
1,UFC Fight Night: Burns vs. Malott,Kyler Phillips vs. Charles Jourdain,L/W,Bantamweight Bout,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Jerin Valel,Junichiro Kamijo 28 - 29.Sal D'amato 28 - 29.J...,http://ufcstats.com/fight-details/b5299e5b9460...
2,UFC Fight Night: Burns vs. Malott,Mandel Nallo vs. Jai Herbert,L/W,Lightweight Bout,KO/TKO,1,2:05,3 Rnd (5-5-5),Jason Herzog,Punches to Head On Ground,http://ufcstats.com/fight-details/e644218737c1...
3,UFC Fight Night: Burns vs. Malott,Jasmine Jasudavicius vs. Karine Silva,W/L,Women's Flyweight Bout,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Jerin Valel,Mike Bell 28 - 29.Jason Rodgers 28 - 29.Junich...,http://ufcstats.com/fight-details/5a209522211d...
4,UFC Fight Night: Burns vs. Malott,Thiago Moises vs. Gauge Young,L/W,Lightweight Bout,Decision - Split,3,5:00,3 Rnd (5-5-5),Jason Herzog,Junichiro Kamijo 28 - 29.David Therien 29 - 28...,http://ufcstats.com/fight-details/a661c0bee7c8...

fighters (4486, 4)

,first,last,nickname,url
0,Tom,Aaron,NaN,http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny,Abbadi,The Assassin,http://ufcstats.com/fighter-details/15df64c02b...
2,Nariman,Abbasov,Bayraktar,http://ufcstats.com/fighter-details/59a9d6dac6...
3,Darion,Abbey,NaN,http://ufcstats.com/fighter-details/4961467134...
4,David,Abbott,Tank,http://ufcstats.com/fighter-details/b361180739...

tott (4486, 7)

,fighter,height,weight,reach,stance,dob,url
0,Tom Aaron,--,155 lbs.,--,NaN,"Jul 13, 1978",http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny Abbadi,"5' 11""",155 lbs.,--,Orthodox,"Jul 03, 1983",http://ufcstats.com/fighter-details/15df64c02b...
2,Nariman Abbasov,"5' 8""",155 lbs.,"66""",Orthodox,"Feb 01, 1994",http://ufcstats.com/fighter-details/59a9d6dac6...
3,Darion Abbey,"6' 2""",265 lbs.,"80""",Orthodox,"Feb 25, 1993",http://ufcstats.com/fighter-details/4961467134...
4,David Abbott,"6' 0""",265 lbs.,--,Switch,"Apr 26, 1965",http://ufcstats.com/fighter-details/b361180739...

STEP 2 CLEANED

fighters (4486, 7)

,fighter,weight,height,reach,stance,dob,fighter_url
0,Tom Aaron,155 lbs.,NaN,NaN,NaN,1978-07-13,http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny Abbadi,155 lbs.,71.0,NaN,Orthodox,1983-07-03,http://ufcstats.com/fighter-details/15df64c02b...
2,Nariman Abbasov,155 lbs.,68.0,66.0,Orthodox,1994-02-01,http://ufcstats.com/fighter-details/59a9d6dac6...
3,Darion Abbey,265 lbs.,74.0,80.0,Orthodox,1993-02-25,http://ufcstats.com/fighter-details/4961467134...
4,David Abbott,265 lbs.,72.0,NaN,Switch,1965-04-26,http://ufcstats.com/fighter-details/b361180739...

full_fight_stats (7265, 61)

,bout,event,date,location,fighter_a,fighter_b,winner,loser,weightclass,finish,...,b_five_round_fights_entering,b_avg_fight_time_entering,b_win_rate_entering,b_finish_win_rate_entering,b_ko_win_rate_entering,b_sub_win_rate_entering,b_five_round_rate_entering,b_height,b_reach,b_age_at_fight
0,Gilbert Burns vs. Mike Malott,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Gilbert Burns,Mike Malott,Mike Malott,Gilbert Burns,Welterweight,True,...,0.0,550.428571,0.857143,0.571429,0.285714,0.285714,0.0,73.0,73.0,34
1,Kyler Phillips vs. Charles Jourdain,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Kyler Phillips,Charles Jourdain,Charles Jourdain,Kyler Phillips,Bantamweight,False,...,0.0,655.500000,0.571429,0.428571,0.142857,0.285714,0.0,69.0,69.0,30
2,Mandel Nallo vs. Jai Herbert,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Mandel Nallo,Jai Herbert,Jai Herbert,Mandel Nallo,Lightweight,True,...,0.0,674.750000,0.375000,0.125000,0.125000,0.000000,0.0,73.0,77.0,37
3,Thiago Moises vs. Gauge Young,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Thiago Moises,Gauge Young,Gauge Young,Thiago Moises,Lightweight,False,...,0.0,900.000000,0.500000,0.000000,0.000000,0.000000,0.0,69.0,70.0,25
4,Dennis Buzukja vs. Marcio Barbosa,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Dennis Buzukja,Marcio Barbosa,Marcio Barbosa,Dennis Buzukja,Featherweight,True,...,0.0,628.395595,0.000000,0.000000,0.000000,0.000000,0.0,66.0,70.0,27

full_sym (14530, 81)

,bout,event,date,location,fighter_a,fighter_b,winner,loser,weightclass,finish,...,delta_ko_losses_entering,delta_ko_win_rate_entering,delta_ko_wins_entering,delta_losses_entering,delta_reach,delta_sub_losses_entering,delta_sub_win_rate_entering,delta_sub_wins_entering,delta_win_rate_entering,delta_wins_entering
0,Gilbert Burns vs. Mike Malott,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Gilbert Burns,Mike Malott,Mike Malott,Gilbert Burns,Welterweight,True,...,3.0,-0.160714,1.0,8.0,-2.0,0.0,-0.077381,3.0,-0.232143,9.0
1,Kyler Phillips vs. Charles Jourdain,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Kyler Phillips,Charles Jourdain,Charles Jourdain,Kyler Phillips,Bantamweight,False,...,-1.0,-0.031746,-1.0,-3.0,3.0,0.0,-0.174603,-3.0,0.095238,-2.0
2,Mandel Nallo vs. Jai Herbert,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Mandel Nallo,Jai Herbert,Jai Herbert,Mandel Nallo,Lightweight,True,...,-2.0,-0.125000,-1.0,-5.0,-2.0,-1.0,0.000000,0.0,-0.375000,-3.0
3,Thiago Moises vs. Gauge Young,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Thiago Moises,Gauge Young,Gauge Young,Thiago Moises,Lightweight,False,...,3.0,0.066667,1.0,6.0,0.0,1.0,0.200000,3.0,0.033333,7.0
4,Dennis Buzukja vs. Marcio Barbosa,UFC Fight Night: Burns vs. Malott,2026-04-18,"Winnipeg, Manitoba, Canada",Dennis Buzukja,Marcio Barbosa,Marcio Barbosa,Dennis Buzukja,Featherweight,True,...,1.0,0.250000,1.0,3.0,0.0,0.0,0.000000,0.0,0.250000,1.0

fighter_stats (14530, 32)

,bout,event,date,location,weightclass,scheduled_rounds,bout_url,event_url,fighter,fighter_url,...,avg_fight_time_entering,days_since_last_fight,win_rate_entering,finish_win_rate_entering,ko_win_rate_entering,sub_win_rate_entering,five_round_rate_entering,height,reach,age_at_fight
0,MarQuel Mederos vs. Mark Choinski,UFC 316: Dvalishvili vs. O'Malley 2,2025-06-07,"Newark, New Jersey, USA",Lightweight,3,http://ufcstats.com/fight-details/0e8599eca8cc...,http://ufcstats.com/event-details/18c49685296c...,Mark Choinski,http://ufcstats.com/fighter-details/001eb2ab0f...,...,628.395595,-1.0,0.0,0.0,0.0,0.0,0.0,68.0,69.0,29
1,Ray Borg vs. Gabriel Silva,UFC Fight Night: Dos Anjos vs. Edwards,2019-07-20,"San Antonio, Texas, USA",Bantamweight,3,http://ufcstats.com/fight-details/bc01ce748a57...,http://ufcstats.com/event-details/9e0f28d1f639...,Gabriel Silva,http://ufcstats.com/fighter-details/002ca19647...,...,628.395595,-1.0,0.0,0.0,0.0,0.0,0.0,66.0,71.0,24
2,Gabriel Silva vs. Kyler Phillips,UFC Fight Night: Benavidez vs. Figueiredo,2020-02-29,"Norfolk, Virginia, USA",Bantamweight,3,http://ufcstats.com/fight-details/0e3af9b5e1b3...,http://ufcstats.com/event-details/fc9a9559a05f...,Gabriel Silva,http://ufcstats.com/fighter-details/002ca19647...,...,900.000000,224.0,0.0,0.0,0.0,0.0,0.0,66.0,71.0,25
3,Aalon Cruz vs. Spike Carlyle,UFC Fight Night: Benavidez vs. Figueiredo,2020-02-29,"Norfolk, Virginia, USA",Featherweight,3,http://ufcstats.com/fight-details/0bcb04163f8d...,http://ufcstats.com/event-details/fc9a9559a05f...,Aalon Cruz,http://ufcstats.com/fighter-details/003d82fa38...,...,628.395595,-1.0,0.0,0.0,0.0,0.0,0.0,72.0,78.0,30
4,Uros Medic vs. Aalon Cruz,UFC 259: Blachowicz vs. Adesanya,2021-03-06,"Las Vegas, Nevada, USA",Lightweight,3,http://ufcstats.com/fight-details/e2abba69c337...,http://ufcstats.com/event-details/6e2b1d631832...,Aalon Cruz,http://ufcstats.com/fighter-details/003d82fa38...,...,85.000000,371.0,0.0,0.0,0.0,0.0,0.0,72.0,78.0,31

STEP 3 XY, XY_SPLITS

x (14530, 29)

,ppv,scheduled_rounds,delta_age_at_fight,delta_avg_fight_time_entering,delta_days_since_last_fight,delta_fights_entering,delta_finish_losses_entering,delta_finish_win_rate_entering,delta_finish_wins_entering,delta_five_round_fights_entering,...,delta_sub_wins_entering,delta_win_rate_entering,delta_wins_entering,weightclass_Featherweight,weightclass_Flyweight,weightclass_Heavyweight,weightclass_Light Heavyweight,weightclass_Lightweight,weightclass_Middleweight,weightclass_Welterweight
0,1,3,-2,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,0,0,0,0,0,1,0
1,1,3,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0,0,1,0
2,1,3,5,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,0,0,1,0,0,0,0
3,1,3,-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,1,0,0,0,0
4,1,3,1,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,0,0,1,0,0,0,0

y (14530,)

0    0
1    1
2    0
3    1
4    0
Name: y, dtype: int64

x_train (11624, 29)

,ppv,scheduled_rounds,delta_age_at_fight,delta_avg_fight_time_entering,delta_days_since_last_fight,delta_fights_entering,delta_finish_losses_entering,delta_finish_win_rate_entering,delta_finish_wins_entering,delta_five_round_fights_entering,...,delta_sub_wins_entering,delta_win_rate_entering,delta_wins_entering,weightclass_Featherweight,weightclass_Flyweight,weightclass_Heavyweight,weightclass_Light Heavyweight,weightclass_Lightweight,weightclass_Middleweight,weightclass_Welterweight
0,1,3,-2,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,0,0,0,0,0,1,0
1,1,3,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0,0,1,0
2,1,3,5,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,0,0,1,0,0,0,0
3,1,3,-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,1,0,0,0,0
4,1,3,1,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,0,0,1,0,0,0,0

x_test (2906, 29)

,ppv,scheduled_rounds,delta_age_at_fight,delta_avg_fight_time_entering,delta_days_since_last_fight,delta_fights_entering,delta_finish_losses_entering,delta_finish_win_rate_entering,delta_finish_wins_entering,delta_five_round_fights_entering,...,delta_sub_wins_entering,delta_win_rate_entering,delta_wins_entering,weightclass_Featherweight,weightclass_Flyweight,weightclass_Heavyweight,weightclass_Light Heavyweight,weightclass_Lightweight,weightclass_Middleweight,weightclass_Welterweight
0,0,3,-1,204.125,-98.0,-4.0,-4.0,-0.000,-2.0,-0.0,...,-4.0,0.125,-1.0,0,0,0,1,0,0,0
1,0,3,1,-204.125,98.0,4.0,4.0,0.000,2.0,0.0,...,4.0,-0.125,1.0,0,0,0,1,0,0,0
2,0,3,-3,308.750,-161.0,1.0,-0.0,-0.100,-0.0,-0.0,...,-0.0,-0.100,-0.0,0,0,0,0,0,1,0
3,0,3,3,-308.750,161.0,-1.0,0.0,0.100,0.0,0.0,...,0.0,0.100,0.0,0,0,0,0,0,1,0
4,0,3,6,-210.125,119.0,6.0,2.0,0.125,1.0,-0.0,...,1.0,-0.250,1.0,0,0,0,0,0,0,0

y_train (11624,)

0    0
1    1
2    0
3    1
4    0
Name: y, dtype: int64

y_test (2906,)

0    1
1    0
2    1
3    0
4    0
Name: y, dtype: int64

STEP 4 MODELS

LOGREG:

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler()),
                ('clf', LogisticRegression(max_iter=5000))])

train accuracy: 0.6037508602890571
test  accuracy: 0.6159669649002064
train roc_auc: 0.6389828351906419
test  roc_auc: 0.6671935369733645
fraction close calls: 0.3262216104611149


BOOSTED:

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('clf',
                 HistGradientBoostingClassifier(l2_regularization=5.0,
                                                learning_rate=0.03, max_depth=3,
                                                max_iter=1200,
                                                min_samples_leaf=50,
                                                random_state=42))])

train accuracy: 0.6163110805230557
test  accuracy: 0.6025464556090847
train roc_auc: 0.6611656964090245
test  roc_auc: 0.6556773867485408
fraction close calls: 0.37611837577426016

STEP 4.5 ODDS RATIOS

                           feature  coefficient  odds_ratio
21             delta_wins_entering     0.261067    1.298315
10  delta_five_round_rate_entering     0.228027    1.256120
20         delta_win_rate_entering     0.170392    1.185769
3    delta_avg_fight_time_entering     0.122521    1.130342
5            delta_fights_entering     0.086330    1.090166

                             feature  coefficient  odds_ratio
12          delta_ko_losses_entering    -0.036556    0.964105
14            delta_ko_wins_entering    -0.054030    0.947404
9   delta_five_round_fights_entering    -0.149995    0.860713
15             delta_losses_entering    -0.188998    0.827788
2                 delta_age_at_fight    -0.314207    0.730368

STEP 5 SCRAPE UPCOMING EVENT INFO


name: UFC Fight Night: Sterling vs. Zalal
url: http://ufcstats.com/event-details/e60d773a0a42048a
date_str: April 25, 2026
date: 2026-04-25 00:00:00
fights: [{'fighter_a': 'Aljamain Sterling', 'fighter_b': 'Youssef Zalal'}, {'fighter_a': 'Norma Dumont', 'fighter_b': 'Joselyne Edwards'}, {'fighter_a': 'Rafa Garcia', 'fighter_b': 'Alexander Hernandez'}, {'fighter_a': 'Davey Grant', 'fighter_b': 'Juan Adrian Martinetti'}, {'fighter_a': 'Montel Jackson', 'fighter_b': 'Raoni Barcelos'}, {'fighter_a': 'Marcus Buchecha', 'fighter_b': 'Ryan Spann'}, {'fighter_a': 'Rodolfo Vieira', 'fighter_b': 'Eric McConico'}, {'fighter_a': 'Jackson McVey', 'fighter_b': 'Sedriques Dumas'}, {'fighter_a': 'Mayra Bueno Silva', 'fighter_b': 'Michelle Montague'}, {'fighter_a': 'Jafel Filho', 'fighter_b': 'Lucas Rocha'}, {'fighter_a': 'Talita Alencar', 'fighter_b': 'Julia Polastri'}]

name: UFC Fight Night: Della Maddalena vs. Prates
url: http://ufcstats.com/event-details/872b018076f831b0
date_str: May 02, 2026
date: 2026-05-02 00:00:00
fights: [{'fighter_a': 'Jack Della Maddalena', 'fighter_b': 'Carlos Prates'}, {'fighter_a': 'Beneil Dariush', 'fighter_b': 'Quillan Salkilld'}, {'fighter_a': 'Tim Elliott', 'fighter_b': 'Steve Erceg'}, {'fighter_a': 'Shamil Gaziev', 'fighter_b': 'Brando Pericic'}, {'fighter_a': 'Tai Tuivasa', 'fighter_b': 'Sean Sharaf'}, {'fighter_a': 'Cam Rowston', 'fighter_b': 'Robert Bryczek'}, {'fighter_a': 'Junior Tafa', 'fighter_b': 'Kevin Christian'}, {'fighter_a': 'Jacob Malkoun', 'fighter_b': 'Gerald Meerschaert'}, {'fighter_a': 'Colby Thicknesse', 'fighter_b': 'Vince Morales'}, {'fighter_a': 'Benjamin Johnston', 'fighter_b': 'Wes Schultz'}, {'fighter_a': 'Jonathan Micallef', 'fighter_b': 'Themba Gorimbo'}, {'fighter_a': 'Dom Mar Fan', 'fighter_b': 'Kody Steele'}]

name: UFC 328: Chimaev vs. Strickland
url: http://ufcstats.com/event-details/9eedac48b497de5a
date_str: May 09, 2026
date: 2026-05-09 00:00:00
fights: [{'fighter_a': 'Khamzat Chimaev', 'fighter_b': 'Sean Strickland'}, {'fighter_a': 'Joshua Van', 'fighter_b': 'Tatsuro Taira'}, {'fighter_a': 'Alexander Volkov', 'fighter_b': 'Waldo Cortes Acosta'}, {'fighter_a': 'Sean Brady', 'fighter_b': 'Joaquin Buckley'}, {'fighter_a': 'King Green', 'fighter_b': 'Jeremy Stephens'}, {'fighter_a': 'Jan Blachowicz', 'fighter_b': 'Bogdan Guskov'}, {'fighter_a': 'Ateba Gautier', 'fighter_b': 'Ozzy Diaz'}, {'fighter_a': 'Joel Alvarez', 'fighter_b': 'Yaroslav Amosov'}, {'fighter_a': 'Roman Kopylov', 'fighter_b': 'Marco Tulio'}, {'fighter_a': 'Baisangur Susurkaev', 'fighter_b': 'Djorden Santos'}, {'fighter_a': 'Clayton Carpenter', 'fighter_b': 'Jose Ochoa'}, {'fighter_a': 'Grant Dawson', 'fighter_b': 'Mateusz Rebecki'}]

name: UFC Fight Night: Allen vs. Costa
url: http://ufcstats.com/event-details/73abb7a5c57fb443
date_str: May 16, 2026
date: 2026-05-16 00:00:00
fights: [{'fighter_a': 'Arnold Allen', 'fighter_b': 'Melquizael Costa'}, {'fighter_a': 'Shauna Bannon', 'fighter_b': 'Nicolle Caliari'}, {'fighter_a': 'Ketlen Vieira', 'fighter_b': 'Jacqueline Cavalcanti'}, {'fighter_a': 'Daniel Barez', 'fighter_b': 'Luis Gurule'}, {'fighter_a': 'Timmy Cuamba', 'fighter_b': 'Benardo Sopaj'}, {'fighter_a': 'Tuco Tokkos', 'fighter_b': 'Ivan Erslan'}, {'fighter_a': 'Modestas Bukauskas', 'fighter_b': 'Rodolfo Bellato'}, {'fighter_a': 'Alice Ardelean', 'fighter_b': 'Polyana Viana'}, {'fighter_a': 'Dooho Choi', 'fighter_b': 'Daniel Santos'}, {'fighter_a': 'Malcolm Wellmaker', 'fighter_b': 'Juan Diaz'}, {'fighter_a': 'Jeremiah Wells', 'fighter_b': 'Nicolas Dalby'}, {'fighter_a': 'Trey Ogden', 'fighter_b': 'Tommy Gantt'}, {'fighter_a': 'Cody Brundage', 'fighter_b': 'Andre Petroski'}]

name: UFC Fight Night: Song vs. Figueiredo
url: http://ufcstats.com/event-details/1e75e6c9de99fa76
date_str: May 30, 2026
date: 2026-05-30 00:00:00
fights: [{'fighter_a': 'Song Yadong', 'fighter_b': 'Deiveson Figueiredo'}, {'fighter_a': 'Sergei Pavlovich', 'fighter_b': 'Tallison Teixeira'}, {'fighter_a': 'Zhang Mingyang', 'fighter_b': 'Alonzo Menifield'}, {'fighter_a': 'Alex Perez', 'fighter_b': 'Sumudaerji'}, {'fighter_a': 'Loma Lookboonmee', 'fighter_b': 'Jaqueline Amorim'}, {'fighter_a': 'Yi Sak Lee', 'fighter_b': 'Luis Felipe Dias'}, {'fighter_a': 'Rei Tsuruya', 'fighter_b': 'Jesus Aguilar'}, {'fighter_a': 'Aoriqileng', 'fighter_b': 'Cody Haddon'}, {'fighter_a': 'Kai Asakura', 'fighter_b': 'Cameron Smotherman'}, {'fighter_a': 'Angela Hill', 'fighter_b': 'Xiong Jingnan'}, {'fighter_a': 'Muslim Salikhov', 'fighter_b': 'Jake Matthews'}]

name: UFC Fight Night: Muhammad vs. Bonfim
url: http://ufcstats.com/event-details/ba17afef01ed78b6
date_str: June 06, 2026
date: 2026-06-06 00:00:00
fights: [{'fighter_a': 'Belal Muhammad', 'fighter_b': 'Gabriel Bonfim'}, {'fighter_a': 'Iwo Baraniewski', 'fighter_b': 'Billy Elekana'}, {'fighter_a': 'Imanol Rodriguez', 'fighter_b': 'Matt Schnell'}, {'fighter_a': 'Bruno Silva', 'fighter_b': 'Edgar Chairez'}, {'fighter_a': 'Jeisla Chaves', 'fighter_b': 'Yuneisy Duben'}]

name: UFC Freedom 250
url: http://ufcstats.com/event-details/48544433372ecfa6
date_str: June 14, 2026
date: 2026-06-14 00:00:00
fights: [{'fighter_a': 'Ilia Topuria', 'fighter_b': 'Justin Gaethje'}, {'fighter_a': 'Alex Pereira', 'fighter_b': 'Ciryl Gane'}, {'fighter_a': "Sean O'Malley", 'fighter_b': 'Aiemann Zahabi'}, {'fighter_a': 'Mauricio Ruffy', 'fighter_b': 'Michael Chandler'}, {'fighter_a': 'Bo Nickal', 'fighter_b': 'Kyle Daukaus'}, {'fighter_a': 'Diego Lopes', 'fighter_b': 'Steve Garcia'}, {'fighter_a': 'Josh Hokit', 'fighter_b': 'Derrick Lewis'}]

name: UFC Fight Night
url: http://ufcstats.com/event-details/c8661e204c66f325
date_str: June 20, 2026
date: 2026-06-20 00:00:00
fights: [{'fighter_a': 'Allan Nascimento', 'fighter_b': 'Mitch Raposo'}]

name: UFC 329
url: http://ufcstats.com/event-details/fccb0fee256b7b4d
date_str: July 11, 2026
date: 2026-07-11 00:00:00
fights: []

name: UFC 330
url: http://ufcstats.com/event-details/b96619b3acd7d9da
date_str: August 15, 2026
date: 2026-08-15 00:00:00
fights: []

STEP 6 PREDICT ALL UPCOMING FIGHTS


UFC Fight Night: Sterling vs. Zalal (2026-04-25)
Aljamain Sterling vs. Youssef Zalal -> Aljamain Sterling (0.520)
Norma Dumont vs. Joselyne Edwards -> could not predict
Rafa Garcia vs. Alexander Hernandez -> Rafa Garcia (0.532)
Davey Grant vs. Juan Adrian Martinetti -> could not predict
Montel Jackson vs. Raoni Barcelos -> Montel Jackson (0.623)
Marcus Buchecha vs. Ryan Spann -> Ryan Spann (0.665)
Rodolfo Vieira vs. Eric McConico -> Rodolfo Vieira (0.602)
Jackson McVey vs. Sedriques Dumas -> Sedriques Dumas (0.522)
Mayra Bueno Silva vs. Michelle Montague -> could not predict
Jafel Filho vs. Lucas Rocha -> Jafel Filho (0.530)
Talita Alencar vs. Julia Polastri -> could not predict

UFC Fight Night: Della Maddalena vs. Prates (2026-05-02)
Jack Della Maddalena vs. Carlos Prates -> Jack Della Maddalena (0.552)
Beneil Dariush vs. Quillan Salkilld -> Quillan Salkilld (0.548)
Tim Elliott vs. Steve Erceg -> Steve Erceg (0.678)
Shamil Gaziev vs. Brando Pericic -> Brando Pericic (0.516)
Tai Tuivasa vs. Sean Sharaf -> Tai Tuivasa (0.583)
Cam Rowston vs. Robert Bryczek -> Cam Rowston (0.701)
Junior Tafa vs. Kevin Christian -> Junior Tafa (0.526)
Jacob Malkoun vs. Gerald Meerschaert -> Jacob Malkoun (0.562)
Colby Thicknesse vs. Vince Morales -> Colby Thicknesse (0.641)
Benjamin Johnston vs. Wes Schultz -> could not predict
Jonathan Micallef vs. Themba Gorimbo -> Jonathan Micallef (0.640)
Dom Mar Fan vs. Kody Steele -> could not predict

UFC 328: Chimaev vs. Strickland (2026-05-09)
Khamzat Chimaev vs. Sean Strickland -> Khamzat Chimaev (0.568)
Joshua Van vs. Tatsuro Taira -> Tatsuro Taira (0.552)
Alexander Volkov vs. Waldo Cortes Acosta -> could not predict
Sean Brady vs. Joaquin Buckley -> Sean Brady (0.588)
King Green vs. Jeremy Stephens -> King Green (0.601)
Jan Blachowicz vs. Bogdan Guskov -> Bogdan Guskov (0.582)
Ateba Gautier vs. Ozzy Diaz -> Ateba Gautier (0.845)
Joel Alvarez vs. Yaroslav Amosov -> Joel Alvarez (0.680)
Roman Kopylov vs. Marco Tulio -> Marco Tulio (0.587)
Baisangur Susurkaev vs. Djorden Santos -> Baisangur Susurkaev (0.680)
Clayton Carpenter vs. Jose Ochoa -> Jose Ochoa (0.544)
Grant Dawson vs. Mateusz Rebecki -> Grant Dawson (0.727)

UFC Fight Night: Allen vs. Costa (2026-05-16)
Arnold Allen vs. Melquizael Costa -> Arnold Allen (0.589)
Shauna Bannon vs. Nicolle Caliari -> could not predict
Ketlen Vieira vs. Jacqueline Cavalcanti -> could not predict
Daniel Barez vs. Luis Gurule -> Daniel Barez (0.525)
Timmy Cuamba vs. Benardo Sopaj -> Timmy Cuamba (0.552)
Tuco Tokkos vs. Ivan Erslan -> Ivan Erslan (0.527)
Modestas Bukauskas vs. Rodolfo Bellato -> Rodolfo Bellato (0.509)
Alice Ardelean vs. Polyana Viana -> could not predict
Dooho Choi vs. Daniel Santos -> Daniel Santos (0.535)
Malcolm Wellmaker vs. Juan Diaz -> could not predict
Jeremiah Wells vs. Nicolas Dalby -> Jeremiah Wells (0.527)
Trey Ogden vs. Tommy Gantt -> could not predict
Cody Brundage vs. Andre Petroski -> Andre Petroski (0.638)

UFC Fight Night: Song vs. Figueiredo (2026-05-30)
Song Yadong vs. Deiveson Figueiredo -> Song Yadong (0.642)
Sergei Pavlovich vs. Tallison Teixeira -> Tallison Teixeira (0.634)
Zhang Mingyang vs. Alonzo Menifield -> Zhang Mingyang (0.669)
Alex Perez vs. Sumudaerji -> Sumudaerji (0.593)
Loma Lookboonmee vs. Jaqueline Amorim -> could not predict
Yi Sak Lee vs. Luis Felipe Dias -> could not predict
Rei Tsuruya vs. Jesus Aguilar -> Rei Tsuruya (0.650)
Aoriqileng vs. Cody Haddon -> Cody Haddon (0.524)
Kai Asakura vs. Cameron Smotherman -> Kai Asakura (0.634)
Angela Hill vs. Xiong Jingnan -> could not predict
Muslim Salikhov vs. Jake Matthews -> Jake Matthews (0.769)

UFC Fight Night: Muhammad vs. Bonfim (2026-06-06)
Belal Muhammad vs. Gabriel Bonfim -> Belal Muhammad (0.529)
Iwo Baraniewski vs. Billy Elekana -> Iwo Baraniewski (0.577)
Imanol Rodriguez vs. Matt Schnell -> Imanol Rodriguez (0.569)
Bruno Silva vs. Edgar Chairez -> Edgar Chairez (0.634)
Jeisla Chaves vs. Yuneisy Duben -> could not predict

UFC Freedom 250 (2026-06-14)
Ilia Topuria vs. Justin Gaethje -> Ilia Topuria (0.735)
Alex Pereira vs. Ciryl Gane -> Ciryl Gane (0.582)
Sean O'Malley vs. Aiemann Zahabi -> Sean O'Malley (0.685)
Mauricio Ruffy vs. Michael Chandler -> Mauricio Ruffy (0.678)
Bo Nickal vs. Kyle Daukaus -> Bo Nickal (0.684)
Diego Lopes vs. Steve Garcia -> Diego Lopes (0.587)
Josh Hokit vs. Derrick Lewis -> Josh Hokit (0.728)

UFC Fight Night (2026-06-20)
Allan Nascimento vs. Mitch Raposo -> Allan Nascimento (0.531)

UFC 329 (2026-07-11)

UFC 330 (2026-08-15)

STEP 7 STORE PREDICTIONS IN DB

,event,date,fighter_a,fighter_b,prob_fighter_a_wins,prob_fighter_b_wins,predicted_winner
0,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Aljamain Sterling,Youssef Zalal,0.519933,0.480067,Aljamain Sterling
1,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Norma Dumont,Joselyne Edwards,NaN,NaN,None
2,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Rafa Garcia,Alexander Hernandez,0.531725,0.468275,Rafa Garcia
3,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Davey Grant,Juan Adrian Martinetti,NaN,NaN,None
4,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Montel Jackson,Raoni Barcelos,0.622507,0.377493,Montel Jackson
5,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Marcus Buchecha,Ryan Spann,0.335311,0.664689,Ryan Spann
6,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Rodolfo Vieira,Eric McConico,0.601618,0.398382,Rodolfo Vieira
7,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Jackson McVey,Sedriques Dumas,0.477670,0.522330,Sedriques Dumas
8,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Mayra Bueno Silva,Michelle Montague,NaN,NaN,None
9,UFC Fight Night: Sterling vs. Zalal,2026-04-25,Jafel Filho,Lucas Rocha,0.530194,0.469806,Jafel Filho